#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="8.2.4"
URL="http://www.phpnuke.org/modules/Release/files/phpnuke-release-${VERSION}.tar.gz"

dl $URL /usr/local/src

