#!/bin/bash -ex

VERSION="phpnuke-release-8.2.4.tar.gz"
URL="http://www.phpnuke.org/modules/Release/files/$VERSION"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY="$FAB_HTTP_PROXY"
wget $URL -O /usr/local/src/$VERSION
unset HTTP_PROXY

