#!/bin/sh -ex

DB_NAME=phpnuke
DB_USER=phpnuke
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/phpnuke

# unpack and set permissions
tar -zxf $SRC/phpnuke-release-*.tar.gz -C $SRC
mv $SRC/phpnuke/html $WEBROOT
mkdir -p $WEBROOT/docs
mv $SRC/phpnuke/*.txt $WEBROOT/docs
rm -rf $SRC/phpnuke-*
chown -R root:root $WEBROOT
chown www-data:www-data $WEBROOT/ultramode.txt
chown www-data:www-data $WEBROOT/config.php

# configure apache
a2dissite default
a2ensite phpnuke
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# preseed db configuration and import schema
CONF=$WEBROOT/config.php
sed -i "s|^\$dbuname.*|\$dbuname = \"$DB_USER\";|" $CONF
sed -i "s|^\$dbpass.*|\$dbpass = \"$DB_PASS\";|" $CONF
sed -i "s|^\$dbname.*|\$dbname = \"$DB_NAME\";|" $CONF

SQLDUMP=$WEBROOT/install/sql/nuke.sql
mysql --user=root --password=$MYSQL_PASS $DB_NAME < $SQLDUMP

# create super user
MD5_PASS=$(echo -n $ADMIN_PASS | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO nuke_authors VALUES ('admin', 'God', '', '$ADMIN_MAIL', '$MD5_PASS', 0, 1, '');"

# tweak settings
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE nuke_config SET sitename=\"TurnKey PHPNuke\", adminmail=\"$ADMIN_MAIL\", notify_email=\"$ADMIN_MAIL\";"

# stop services
/etc/init.d/mysql stop

