#!/bin/sh -ex

DB_NAME=phpnuke
DB_USER=phpnuke
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/phpnuke

# unpack and set permissions
tar -zxf $SRC/phpnuke-release-*.tar.gz -C $SRC
mv $SRC/phpnuke/html $WEBROOT
mkdir -p $WEBROOT/docs
mv $SRC/phpnuke/*.txt $WEBROOT/docs
rm -rf $SRC/phpnuke-*
chown -R root:root $WEBROOT
chown www-data:www-data $WEBROOT/ultramode.txt
chown www-data:www-data $WEBROOT/config.php

# configure apache
a2dissite default
a2ensite phpnuke
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

