#!/bin/bash -e
# regenerate phpnuke secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/phpnuke/config.php
SITEKEY=$(mcookie)
PASSWORD=$(mcookie)

sed -i "s|^\$sitekey.*|\$sitekey = \"$SITEKEY\";|" $CONF
sed -i "s|^\$dbpass.*|\$dbpass = \"$PASSWORD\";|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=phpnuke --pass="$PASSWORD"

